a = input('Masukkan sekumpulan bilangan (pisahkan dengan koma): ').split(', ')
e = max(a, key = lambda x : int(x))
f = min(a, key = lambda x : int(x))
print(f"Bilangan terbesar dari kumpulan bilangan yang di input adalah {e}")
print(f"Bilangan terkecil dari kumpulan bilangan yang di input adalah {f}")